name: le10del10
description: App del disco Le 10 del 10
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase (nÃºcleo + autenticaciÃ³n para login futuro)
  firebase_core: ^3.15.2
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1 # <-- AÃ‘ADIDO

  # ðŸŽ§ Audio y multimedia
  audioplayers: ^6.5.1
  just_audio: ^0.9.46
  audio_service: ^0.18.10
  audio_session: ^0.1.16

  # ðŸŒ Utilidades
  url_launcher: ^6.3.0
  youtube_player_flutter: ^9.1.3
  equatable: ^2.0.5
  cloud_firestore: ^5.4.4
  http: ^1.2.2
  shared_preferences: ^2.3.2

  # ðŸŽ¨ Estilo iOS
  cupertino_icons: ^1.0.8
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/portada.PNG"

flutter:
  uses-material-design: true
  assets:
    - assets/
